/// Flutter icons AceleracaoIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AceleracaoIcon
///      fonts:
///       - asset: fonts/AceleracaoIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AceleracaoIcon {
  AceleracaoIcon._();

  static const _kFontFam = 'aceleracao';
  static const _kFontPkg = null;

  static const IconData alpha =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
