/// Flutter icons DistanceIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DistanceIcon
///      fonts:
///       - asset: fonts/DistanceIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DistanceIcon {
  DistanceIcon._();

  static const _kFontFam = 'icomoon';
  static const _kFontPkg = null;

  static const IconData distance =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
