name: game4code_front
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  appinio_swiper: ^1.0.3
  #audioplayers: ^1.0.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.18.3
  flutter_progress_button: ^1.0.0
  flutter_slidable: ^2.0.0
  flutter_speed_dial: ^6.1.0+1
  flutter_swiper: ^1.1.6
  hooks_riverpod: ^1.0.3
  hop_swipe_cards: ^1.0.0+1
  http: ^0.13.4
  material_design_icons_flutter: ^5.0.6595
  scaffold_gradient_background: ^1.0.3+1
  simple_speed_dial: ^0.1.7
  swipe_cards: ^1.0.0
  swipeable_card_stack: ^0.0.5
  tcard: ^1.3.5
  flip_card: ^0.6.0
  rflutter_alert: ^2.0.4

dev_dependencies:

  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path_android: "assets/Icon/mipmap-xxxhdpi/Phy Icon.png"

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 500
    - family: icomoon
      fonts:
        - asset: assets/fonts/javaicon.ttf
        - asset: assets/fonts/rubygems.ttf
          weight: 500
    - family: gems
      fonts:
        - asset: assets/fonts/gems.ttf
          weight: 500
  assets:
    - assets/imagens/
