name: g4c
description: GAME4CODE - Um TCC Flutter projeto.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  sqflite:
#  path:
  flutter_progress_button: ^1.0.0
  material_design_icons_flutter: ^5.0.6595
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: false
  image_path_android: "assets/Icon/mipmap-xxxhdpi/Phy Icon.png"

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-Bold.ttf
          weight: 500
    - family: icomoon
      fonts:
        - asset: fonts/javaicon.ttf
        - asset: fonts/rubygems.ttf
          weight: 500
    - family: gems
      fonts:
        - asset: fonts/gems.ttf
          weight: 500
  assets:
   - assets/profile_logo/
   - assets/appBar/
   - assets/bottom_navigation_bar/
