/// Flutter icons DistanceIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DistanceIcon
///      fonts:
///       - asset: fonts/DistanceIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'icomoon';
  static const dynamic _kFontPkg = null;

  static const IconData java =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Gems {
  Gems._();

  static const String _fontFamily = 'gems';

  static const IconData rubygems = IconData(0xe901, fontFamily: _fontFamily);
}
